### Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [10]:
x = [10,20,30,40,50]
type(x)

list

In [11]:
x.append(60) #Append 
print(x)

[10, 20, 30, 40, 50, 60]


In [12]:
x.extend([70,80]) #Extend
print(x)

[10, 20, 30, 40, 50, 60, 70, 80]


In [13]:
x.insert(2,25) #Insert
print(x)

[10, 20, 25, 30, 40, 50, 60, 70, 80]


In [14]:
x.remove(25) #Remove
print(x)

[10, 20, 30, 40, 50, 60, 70, 80]


In [15]:
x.pop() #Pop
print(x)

[10, 20, 30, 40, 50, 60, 70]


In [17]:
x.index(30) #Index

2

In [18]:
x.count(20) #Count

1

In [19]:
x.sort() #Sort
print(x)

[10, 20, 30, 40, 50, 60, 70]


In [20]:
x.reverse() #Reverse
print(x)

[70, 60, 50, 40, 30, 20, 10]


In [21]:
x.clear() #Clear
print(x)

[]


#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [22]:
tup = ("Tom", "Oggy", "Rio")
type(tup)

tuple

In [23]:
tup[1] = 'Eros'

TypeError: 'tuple' object does not support item assignment

##### Explanation :
- A tuple is immutable in Python.
- Immutable means once created, its elements cannot be changed.
- That’s why changing the second name in a tuple causes a TypeError.

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [34]:
set1 = {20,10,20,30,30,40,40,50}
type(set1)

set

In [35]:
set1

{10, 20, 30, 40, 50}

### Explanation :

- A set in Python stores only unique elements.
- Duplicate values are automatically removed when the set is created.

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [37]:
dic = {
    'name' : 'Rio' ,
    'age' : 21 ,
    'city' : 'Ahmedabad '
} # Creating Dictionary
type(dic)

dict

In [38]:
dic["age"] = 22 #Update
dic['Email'] = 'rio0099@gmail.com' #Add New Key 

In [39]:
print(dic)

{'name': 'Rio', 'age': 22, 'city': 'Ahmedabad ', 'Email': 'rio0099@gmail.com'}


#### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [40]:
age = int(input("Enter The Age :")) 
if age >= 18 :
    print("Person Is Eligible ")
else :
    print("Person Is Not Eligible")

Enter The Age : 20


Person Is Eligible 


#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [44]:
marks = int(input("Enter  Marks Here :"))
if marks >= 90 :
    print("Your Grade Is A")
elif marks >= 75 and marks < 90 :
    print("Your Grade Is B")
elif marks >= 50 and marks <75 :
    print("Your Grade Is C")
else :
    print("Ohh No..! Your Are Failed")

Enter  Marks Here : 100


Your Grade Is A


#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [50]:
num = int(input("Enter Any Number Here : "))
if num > 0 :
    print("Number Is Positive")
    if num % 2 == 0 :
        print("Number Is also Even")
    else :
        print("Number Is Odd")
elif num == 0 :
    print("Number Is Zero")
else :
    print("Numer Is Negative")

Enter Any Number Here :  10


Number Is Positive
Number Is also Even


### Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [54]:
import numpy as np
# A scalar using np.array(5)
scalar = np.array(5)
print(f"Scalar : {scalar}")
print(f"Shape : {scalar.shape}")

Scalar : 5
Shape : ()


In [63]:
# A 1D array with values 1 to 5
array_1d = np.array([1,2,3,4,5])
print(f"1D Array : {array_1d}")
print(f"Shape : {array_1d.shape}")

1D Array : [1 2 3 4 5]
Shape : (5,)


In [65]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10,20,30],[40,50,60]])
print(f"2D Array :\n {array_2d}")
print(f"Shape : {array_2d.shape}")

2D Array :
 [[10 20 30]
 [40 50 60]]
Shape : (2, 3)


#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint()10


In [66]:
random_array = np.random.randint(0, 101 , size = (4, 4))
print(f"4x4 Random Integer Array:\n {random_array}")

4x4 Random Integer Array:
 [[49 66 61 73]
 [43 96 44 83]
 [96 92 44 97]
 [59 69 23 56]]


#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [69]:
import numpy as np 
import pandas as pd

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) #Creating a 2d array

df = pd.DataFrame(arr , columns = ["A", "B", "C"]) #Creating A pandas Dataframe 
print(df)
print(type(df))

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90
<class 'pandas.core.frame.DataFrame'>


### Section C: Exploring Pandas

#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [72]:
import numpy as np
import pandas as pd

data = {
    "Name" : ["Rio", "Rio", "Neha", "Neha", "Karan", "Smit", "Arun", "Kuldeep", "Maulik", "Khushi"], 
    "Age" : [21, 21, 24, 24, 21, 22, 20, 21, 21, 22],
    "City" :["Mumbai", "Mumbai", "Pune", "Pune", "Surat", "Delhi", "Mumbai", "Jaipur", "Indore", "Ahmedabad"],
     "Salary": [50000, 50000, 55000, 55000, 65000, 50000, np.nan, 70000, np.nan, 55000]
}

df = pd.DataFrame(data) #Creating Dataframe
df

Name  Age       City   Salary
0      Rio   21     Mumbai  50000.0
1      Rio   21     Mumbai  50000.0
2     Neha   24       Pune  55000.0
3     Neha   24       Pune  55000.0
4    Karan   21      Surat  65000.0
5     Smit   22      Delhi  50000.0
6     Arun   20     Mumbai      NaN
7  Kuldeep   21     Jaipur  70000.0
8   Maulik   21     Indore      NaN
9   Khushi   22  Ahmedabad  55000.0

In [73]:
df.info() #info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [74]:
df.describe() #Describe

Age        Salary
count  10.000000      8.000000
mean   21.700000  56250.000000
std     1.337494   7440.238091
min    20.000000  50000.000000
25%    21.000000  50000.000000
50%    21.000000  55000.000000
75%    22.000000  57500.000000
max    24.000000  70000.000000

In [75]:
df[["Name", "City"]] #Select 'Name' and 'City' columns

Name       City
0      Rio     Mumbai
1      Rio     Mumbai
2     Neha       Pune
3     Neha       Pune
4    Karan      Surat
5     Smit      Delhi
6     Arun     Mumbai
7  Kuldeep     Jaipur
8   Maulik     Indore
9   Khushi  Ahmedabad

In [79]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())#Fill any missing values in 'Salary' column with the mean
df

Name  Age       City   Salary
0      Rio   21     Mumbai  50000.0
1      Rio   21     Mumbai  50000.0
2     Neha   24       Pune  55000.0
3     Neha   24       Pune  55000.0
4    Karan   21      Surat  65000.0
5     Smit   22      Delhi  50000.0
6     Arun   20     Mumbai  56250.0
7  Kuldeep   21     Jaipur  70000.0
8   Maulik   21     Indore  56250.0
9   Khushi   22  Ahmedabad  55000.0

In [81]:
new_df = df.drop_duplicates() #Remove any duplicate rows
new_df

Name  Age       City   Salary
0      Rio   21     Mumbai  50000.0
2     Neha   24       Pune  55000.0
4    Karan   21      Surat  65000.0
5     Smit   22      Delhi  50000.0
6     Arun   20     Mumbai  56250.0
7  Kuldeep   21     Jaipur  70000.0
8   Maulik   21     Indore  56250.0
9   Khushi   22  Ahmedabad  55000.0